blank_issues_enabled: false
contact_links:
  - name: 'ğŸ’¬ Browse Q&A'
    url: https://github.com/SoCuul/SCInsta/discussions
    about: Find answers to the most commonly asked questions
  - name: 'â“ Need Help?'
    url: https://github.com/SoCuul/SCInsta/discussions
    about: Visit the SCInsta discussions form to get support
